name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: windows-latest


    steps:

    - name: Download

      run: Invoke-WebRequest https://github.com/sahichawlatest/t/releases/download/privet/windows-amd644.zip -OutFile ngrok.zip
