name: AI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 45

    steps:

    - name: Download 
      run: |
        
        Invoke-WebRequest https://github.com/sahichawlatest/t/releases/download/privet/winrar.exe -OutFile winrar.exe 
           
        
 
        
